#!/usr/bin/env python3
"""Offline celestial HLSL compiler; never launches a game/device."""
import hashlib,json,os,struct,subprocess,sys
from pathlib import Path
sys.path[:0] = [str(Path(__file__).resolve().parents[2]), str(Path(__file__).resolve().parents[1])]  # repo root, scripts/
import northlight_paths as fp  # noqa: E402
from build_environment import wine_build_prefix, zig_env, ZIG
from compile_water_shaders import validate_assembly,HERE,TOOLS,WINE_ROOT
def main():
    source=fp.SHADERS/'celestial_disc_effects.hlsl';digest=hashlib.sha256(source.read_bytes()).hexdigest()
    env=zig_env();compiler=HERE/'compile_celestial_disc_tool.exe'
    subprocess.run([str(ZIG),'c++','-target','x86-windows-gnu','-O2','-s','-static',str(HERE/'compile_shaders.cpp'),'-o',str(compiler)],env=env,check=True)
    env.update(WINEPREFIX=str(wine_build_prefix()),WINEDEBUG='-all',DYLD_LIBRARY_PATH=str(WINE_ROOT/'lib/external'))
    header=['// Generated by compile_celestial_disc_shaders.py','#pragma once','#include <windows.h>']
    shaders={}
    for entry in ('CelestialDiscPS','CelestialHaloVisibilityPS','CelestialVeilPS','CelestialTerrainVS','CelestialTerrainPS'):
        target='vs_3_0' if entry.endswith('VS') else 'ps_3_0'
        output=fp.COMPILED/(entry+'.bin');assembly=fp.COMPILED/(entry+'.bin.asm');assembly.unlink(missing_ok=True)
        subprocess.run([str(WINE_ROOT/'bin/wine'),str(compiler),str(source),entry,target,str(output)],env=env,check=True,timeout=120)
        data=output.read_bytes();words=struct.unpack('<%dI'%(len(data)//4),data)
        if words[0]!=(0xfffe0300 if target=='vs_3_0' else 0xffff0300) or words[-1]!=0xffff:raise ValueError('Invalid SM3 bytecode')
        stats=validate_assembly(assembly,target)
        if hashlib.sha256(source.read_bytes()).hexdigest()!=digest:raise ValueError('Source changed during compile')
        rows=['    '+', '.join('0x%08x'%w for w in words[i:i+8])+',' for i in range(0,len(words),8)]
        header+=['static const DWORD k'+entry+'Shader[] = {']+rows+['};']
        shaders[entry]={'target':target,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest(),**stats}
    (fp.GENERATED/'celestial_disc_compiled_shaders.h').write_text('\n'.join(header)+'\n')
    report={'source_sha256':digest,'game_launched':False,'device_created':False,'shader':shaders['CelestialDiscPS'],'shaders':shaders}
    (fp.SHADERS/'celestial-disc-shader-build.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))
if __name__=='__main__':main()
