#!/usr/bin/env python3
"""Offline SM3 compiler only; never creates a device or launches the game."""
import hashlib,json,os,re,struct,subprocess,sys
from pathlib import Path
sys.path[:0] = [str(Path(__file__).resolve().parents[2]), str(Path(__file__).resolve().parents[1])]  # repo root, scripts/
import northlight_paths as fp  # noqa: E402
from build_environment import wine_build_prefix, zig_env, ZIG
from compile_water_shaders import validate_assembly,HERE,TOOLS,WINE_ROOT

def main():
    source=fp.SHADERS/'local_light_effects.hlsl';digest=hashlib.sha256(source.read_bytes()).hexdigest()
    env=zig_env()
    compiler=HERE/'compile_local_light_tool.exe'
    subprocess.run([str(ZIG),'c++','-target','x86-windows-gnu','-O2','-s','-static',str(HERE/'compile_shaders.cpp'),'-o',str(compiler)],env=env,check=True)
    env.update(WINEPREFIX=str(wine_build_prefix()),WINEDEBUG='-all',DYLD_LIBRARY_PATH=str(WINE_ROOT/'lib/external'))
    header=['// Generated by compile_local_light_shaders.py.','#pragma once','#include <windows.h>'];manifest={'source_sha256':digest,'game_launched':False,'device_created':False,'shaders':{}}
    for entry,target in [('LocalShadowVS','vs_3_0'),('LocalShadowPS','ps_3_0'),('LocalLighting','ps_3_0')]:
        output=fp.COMPILED/(entry+'.bin');assembly=fp.COMPILED/(entry+'.bin.asm');assembly.unlink(missing_ok=True)
        subprocess.run([str(WINE_ROOT/'bin/wine'),str(compiler),str(source),entry,target,str(output)],env=env,check=True,timeout=120)
        data=output.read_bytes();words=struct.unpack('<%dI'%(len(data)//4),data)
        if words[0]!=(0xfffe0300 if target.startswith('vs') else 0xffff0300) or words[-1]!=0xffff:raise ValueError('Invalid bytecode')
        stats=validate_assembly(assembly,target)
        # The shared validator handles 2D entries. Cube texldl costs 5 slots,
        # versus 2 for 2D (Microsoft ps_3_0 instruction table, note 2).
        text=assembly.read_text();cube={int(x) for x in re.findall(r'dcl_cube\s+s(\d+)',text)}
        extra=0
        for line in text.splitlines():
            match=re.match(r'\s*(texldl|texldp|texld)\s+.*\bs(\d+)\b',line)
            if match and int(match[2]) in cube:extra+=1 if match[1]=='texldp' else 3
        stats['static_instruction_slots']+=extra;stats['cube_instruction_extra_slots']=extra
        if stats['static_instruction_slots']>512:raise ValueError('SM3 cube instruction slot limit exceeded')
        rows=['    '+', '.join('0x%08x'%w for w in words[i:i+8])+',' for i in range(0,len(words),8)]
        header.append('static const DWORD k%sShader[] = {\n%s\n};'%(entry,'\n'.join(rows)))
        manifest['shaders'][entry]={'target':target,'bytes':len(data),'sha256':hashlib.sha256(data).hexdigest(),**stats}
        print(entry,stats['static_instruction_slots'],'slots',stats['temporary_registers'],'temps',flush=True)
    if hashlib.sha256(source.read_bytes()).hexdigest()!=digest:raise ValueError('Source changed during compilation')
    (fp.GENERATED/'local_light_compiled_shaders.h').write_text('\n\n'.join(header)+'\n')
    (fp.SHADERS/'local-light-shader-build.json').write_text(json.dumps(manifest,indent=2)+'\n')

if __name__=='__main__':main()
