// Generated by renderer/extract_water_shaders.py; do not edit. Exact original liquid shader
// identities (FNV-1a64 of the game's bytecode; no heuristic matching) and the FNV-1a64 and word
// count of the mask variant water_shader_patch.h must build from it. Hashes only, no shader bytes.
#pragma once
#include <cstdint>
struct NorthlightWaterShaderIdentity { std::uint64_t hash; std::uint64_t patchedHash; unsigned patchedWords; bool vertex; };
static const NorthlightWaterShaderIdentity kWaterShaderIdentities[] = {
    {UINT64_C(0x154c2ea13c397f03), UINT64_C(0x9dbe80eb94553990), 366, false},
    {UINT64_C(0x17f042a7906ca126), UINT64_C(0xafe1373f4e88ebda), 64, false},
    {UINT64_C(0x1a60da2b7818d5b8), UINT64_C(0xf4541e19d599c7db), 366, false},
    {UINT64_C(0x1b0033712e29218e), UINT64_C(0x8115a8da5d7fb63e), 341, true},
    {UINT64_C(0x206d861fd0a721dd), UINT64_C(0x5e93bc0101df0b93), 160, true},
    {UINT64_C(0x32e2e79604d9dc80), UINT64_C(0xa10486e4b7ff21f8), 304, false},
    {UINT64_C(0x348db9bfe182895d), UINT64_C(0x4e7048bf5a6c2baa), 296, true},
    {UINT64_C(0x39e3be32b73c3072), UINT64_C(0x09e4e840b6e3587a), 331, true},
    {UINT64_C(0x3b691fe2b8699c90), UINT64_C(0x0997e2fe37d9fd48), 182, true},
    {UINT64_C(0x48a82796bd612aeb), UINT64_C(0xd0026e44bc4bc333), 245, true},
    {UINT64_C(0x4d2a52a4d11bbad4), UINT64_C(0xd99be17003e2fdbd), 150, true},
    {UINT64_C(0x58d812a8b1b84e70), UINT64_C(0x53f32c2f6cf00fb8), 51, false},
    {UINT64_C(0x641e3182221a6adf), UINT64_C(0xac859f3aa8a8aed9), 624, true},
    {UINT64_C(0x6aed203658c81950), UINT64_C(0xa4b78900143e5607), 318, true},
    {UINT64_C(0x6b3ac852d2346d3b), UINT64_C(0x5a9548d63a5e1717), 293, true},
    {UINT64_C(0x70faf83955e2b668), UINT64_C(0xea99a23880ec3d58), 256, true},
    {UINT64_C(0x7267e37a0600359f), UINT64_C(0x24af0102dfeab421), 666, true},
    {UINT64_C(0x75a110398a07c0f5), UINT64_C(0x08f690ca1508d35a), 262, true},
    {UINT64_C(0x7d4f078fa1876a09), UINT64_C(0x2a7cf7d23bb0dadb), 82, false},
    {UINT64_C(0x8abda360b25632f0), UINT64_C(0x85fa833fe4cd6948), 304, false},
    {UINT64_C(0x8fbd18a9917e01f9), UINT64_C(0x5bc452d81d9743a3), 208, true},
    {UINT64_C(0x9ac005ef6269b629), UINT64_C(0x93b2aa9de9421e67), 666, true},
    {UINT64_C(0x9f78f30d80154df0), UINT64_C(0xed6ecdf314e20448), 184, true},
    {UINT64_C(0xa4ef2987a5621125), UINT64_C(0xc3378c79fda41237), 620, true},
    {UINT64_C(0xa4ff11fcf649b8c8), UINT64_C(0xec684fc7bf5b7d0b), 366, false},
    {UINT64_C(0xa63aa6ffcb030f5c), UINT64_C(0x031683df76a72133), 352, true},
    {UINT64_C(0xad7c06a0edfbe512), UINT64_C(0x1988833b2d9367c2), 401, true},
    {UINT64_C(0xb4a68d1d7f52f1af), UINT64_C(0x51b0a96d511aef4b), 304, false},
    {UINT64_C(0xc533c9b728387531), UINT64_C(0x314c997ce87b925e), 261, true},
    {UINT64_C(0xcb5e47465d72644d), UINT64_C(0xc1ec78c20ffae595), 304, true},
    {UINT64_C(0xd61988b2321c47cd), UINT64_C(0xb40ea40b90d5328b), 624, true},
    {UINT64_C(0xe186eee6b5e19eb5), UINT64_C(0x25724390d40e5381), 70, false},
    {UINT64_C(0xeafd290841afcd65), UINT64_C(0x1765dcd8504234bf), 664, true},
    {UINT64_C(0xfb0acc20bc2ba769), UINT64_C(0x8b36b5251c59ec96), 240, true},
    {UINT64_C(0xfb0fb6fd1fffc44c), UINT64_C(0x079fab0a68552339), 206, true},
    {UINT64_C(0xfdd9528ed3ac30ea), UINT64_C(0xfca1df5dee9a3ca9), 197, true},
};
