#!/usr/bin/env python3
"""Build exact-identity water mask variants. No game or graphics device used.
Original deformation, texture sampling, alpha and texkill survive unchanged.
Only supported, fully written output paths receive the two appended MOVs.
Since 0.3.161 the DLL patches the game's own bytecode at shader creation
(src/water/water_shader_patch.h, a port of patch() in water_shader_patch.py,
which stays the reference oracle); this writes only hashes: the original
identity and the FNV-1a64 and word count of the expected mask variant.
"""
import json, re, struct, sys, hashlib
from pathlib import Path
HERE=Path(__file__).resolve().parent
sys.path.insert(0,str(HERE.parent))
import northlight_paths
from mpq import Archive
from extract_signatures import variants, register, fnv1a64
from water_shader_patch import ARITY,reg,dst,src,parse,patch   # re-exported for the tests

PATTERN=re.compile(r'\\(?:vertex|pixel)\\(?:vs|ps)_[123]_\d+\\(?:vs|ps)Liquid(?:ProcWater|Water|WaterNoSpec|Magma)(?:_Editor)?\.bls$',re.I)
def main():
    inventory=json.loads((HERE.parent/'inspection/inventory.json').read_text());found={};excluded=[];variantsSeen=0
    for path,entry in sorted(inventory.items()):
        if not entry['enabled']:continue
        names=[n for n in (HERE.parent/'inspection'/(Path(path).name+'.list')).read_text().splitlines() if PATTERN.search(n)]
        if not names:continue
        with Archive(northlight_paths.client_root()/path) as archive:
            for name in names:
                for index,flags,code in variants(archive.read(name)):
                    variantsSeen+=1;h=fnv1a64(code);r=found.setdefault(h,{'code':code,'sources':[],'excluded':False})
                    if r['code']!=code:raise ValueError('hash collision')
                    r['sources'].append({'archive':path,'path':name,'variant':index})
                    r['excluded']|='magma' in name.lower() or '_editor' in name.lower()
    rows=['// Generated by renderer/extract_water_shaders.py; do not edit. Exact original liquid shader',
          '// identities (FNV-1a64 of the game\'s bytecode; no heuristic matching) and the FNV-1a64 and word',
          '// count of the mask variant water_shader_patch.h must build from it. Hashes only, no shader bytes.',
          '#pragma once','#include <cstdint>',
          'struct NorthlightWaterShaderIdentity { std::uint64_t hash; std::uint64_t patchedHash; unsigned patchedWords; bool vertex; };'];accepted=[]
    for h,r in sorted(found.items()):
        try:
            if r['excluded']:raise ValueError('shared with magma/editor family')
            code,info=patch(r['code'])
        except ValueError as e:
            excluded.append({'hash':f'{h:016x}','reason':str(e),'sources':r['sources']});continue
        accepted.append({'hash':f'{h:016x}','wordCount':len(code)//4,'patched_fnv1a64':f'{fnv1a64(code):016x}','patched_sha256':hashlib.sha256(code).hexdigest(),**info,'sources':r['sources']})
    rows.append('static const NorthlightWaterShaderIdentity kWaterShaderIdentities[] = {')
    for r in accepted:rows.append('    {UINT64_C(0x%s), UINT64_C(0x%s), %d, %s},'%(r['hash'],r['patched_fnv1a64'],r['wordCount'],'true' if r['vertex'] else 'false'))
    rows.append('};')
    (northlight_paths.GAMEDATA/'water_shader_identities.h').write_text('\n'.join(rows)+'\n')
    report={'variants_seen':variantsSeen,'unique':len(found),'accepted':accepted,'excluded':excluded,'game_launched':False}
    (HERE/'water-shader-identities.json').write_text(json.dumps(report,indent=2)+'\n')
    print('Water identity shaders:',len(accepted),'accepted;',len(excluded),'excluded;',variantsSeen,'variants')
    print('Reasons:',{reason:sum(r['reason']==reason for r in excluded) for reason in sorted({r['reason'] for r in excluded})})
def accepted_originals(report=None):
    """(record, original bytecode) for every accepted identity, read from the tester's client MPQs."""
    report=report or json.loads((HERE/'water-shader-identities.json').read_text());archives={}
    try:
        for record in report['accepted']:
            source=record['sources'][0];path=source['archive']
            if path not in archives:archives[path]=Archive(northlight_paths.client_root()/path).__enter__()
            code=next(code for index,_,code in variants(archives[path].read(source['path'])) if index==source['variant'])
            if fnv1a64(code)!=int(record['hash'],16):raise ValueError('original changed: '+record['hash'])
            yield record,code
    finally:
        for archive in archives.values():archive.__exit__(None,None,None)
if __name__=='__main__':main()
