"""Generate private extension fast paths; never alter game-facing guards."""
from pathlib import Path
import re
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import northlight_paths  # noqa: E402
CONTROL = {'BeginStateBlock', 'EndStateBlock', 'CreateStateBlock', 'Reset', 'SetSoftwareVertexProcessing'}
# 0.3.149: not mirrored, so they already went straight to the backend. Counted
# pass-through overrides only (per-type call counts on sampled frames). The mock
# test API has no such methods, so they are left out of that build.
COUNTED = ['DrawIndexedPrimitive', 'DrawPrimitive', 'Clear', 'StretchRect', 'ColorFill', 'SetScissorRect', 'SetTextureStageState']

def generated():
    mirror = northlight_paths.src('device_mirror.h').read_text().split('class MirrorDevice :')[1].split('// Extension calls')[0]
    selected = set(re.findall(r'HRESULT STDMETHODCALLTYPE (\w+)\([^\n]*?override', mirror)) - CONTROL
    # Controls retain mirror recording/failure/Apply behavior even inside raw scopes.
    forwarders = northlight_paths.src('forwarders.h').read_text().split('class ForwardIDirect3DDevice9 :')[1].split('\n};')[0]
    lines = ['// Generated by generate_extension_raw_methods.py. Included inside ExtensionDevice.']
    found, names, counted = set(), [], {}
    for line in forwarders.splitlines():
        name = re.search(r'HRESULT STDMETHODCALLTYPE (\w+)\(', line)
        if name and name.group(1) in COUNTED:
            counted[name.group(1)] = line
        if not name or name.group(1) not in selected:
            continue
        found.add(name.group(1))
        signature, call = line.split('{ return real->', 1)
        call = call.removesuffix(' }')
        lines.append(signature + '{ if(rawActive()){++m->rawCalls;m->countRaw(' + str(len(names)) + ');return real->' + call + '}return MirrorDevice::' + call + ' }')
        names.append(name.group(1))
    assert found == selected, (found, selected)
    assert len(found) == 36, len(found)
    assert sorted(counted) == sorted(COUNTED), counted
    lines.append('#ifndef NORTHLIGHT_DEVICE_MIRROR_TEST_API')
    for name in COUNTED:
        signature, call = counted[name].split('{ return real->', 1)
        lines.append(signature + '{ if(m->rawCounting&&rawActive())m->countRaw(' + str(len(names)) + ');return real->' + call.removesuffix(' }') + ' }')
        names.append(name)
    lines.append('#endif')
    lines.append('    static constexpr unsigned RawMethods=' + str(len(names)) + ';')
    lines.append('    static_assert(RawMethods<=DeviceMirror::RawMethodCapacity,"raw method counters");')
    lines.append('    static const char* rawMethodName(unsigned i){static const char* const names[RawMethods]={' + ','.join('"' + n + '"' for n in names) + '};return i<RawMethods?names[i]:"";}')
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    (northlight_paths.GENERATED / 'extension_raw_methods.inl').write_text(generated())
