"""Serialize inherited game-facing device calls using the shared mirror gate."""
from pathlib import Path
import re
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import northlight_paths  # noqa: E402
# MirrorDevice overrides already take the gate first thing; re-guarding them
# only added a nested acquisition per game call (0.3.136 single-gate switch).
SKIP_SELF_GUARDED = True

def generate():
    body = northlight_paths.src('forwarders.h').read_text().split('class ForwardIDirect3DDevice9 :')[1].split('\n};')[0]
    lines = ['#pragma once', '// Generated by generate_mirror_guarded_device.py. Do not edit.', '#include "device_mirror.h"', 'class GuardedMirrorDevice : public MirrorDevice {', 'public:', '    using MirrorDevice::MirrorDevice;']
    methods = [line for line in body.splitlines() if 'STDMETHODCALLTYPE' in line]
    assert len(methods) == 119
    if SKIP_SELF_GUARDED:
        mirror = northlight_paths.src('device_mirror.h').read_text().split('class MirrorDevice :')[1].split('// Extension calls')[0]
        guarded = set(re.findall(r'STDMETHODCALLTYPE (\w+)\([^\n]*?override\s*\{\s*\n?\s*Guard lock\(m->gate\);', mirror))
        overridden = set(re.findall(r'STDMETHODCALLTYPE (\w+)\([^\n]*?override', mirror))
        assert guarded == overridden and len(guarded) == 41, (overridden - guarded, len(guarded))
        methods = [line for line in methods if re.search(r'STDMETHODCALLTYPE (\w+)\(', line).group(1) not in guarded]
    lines += [line.replace('{ return real->', '{ Guard lock(m->gate);return MirrorDevice::') for line in methods]
    lines.append('};')
    (northlight_paths.GENERATED/'mirror_guarded_device.h').write_text('\n'.join(lines)+'\n')

if __name__ == '__main__':
    generate()
