"""Generate gated forwarding methods for game-visible D3D9 resource proxies."""
from pathlib import Path
import re,sys
ROOT=Path(__file__).resolve().parent
sys.path.insert(0,str(ROOT.parent));import northlight_paths
SDK=northlight_paths.windows_headers()/'d3d9.h'
INTERFACES=('IDirect3DSurface9','IDirect3DTexture9','IDirect3DCubeTexture9','IDirect3DVolumeTexture9','IDirect3DVolume9','IDirect3DVertexShader9','IDirect3DPixelShader9','IDirect3DVertexDeclaration9','IDirect3DQuery9')
def generate():
    source=SDK.read_text();out=['// Generated by generate_mirror_resource_forwarders.py. Do not edit.','#pragma once','#include <d3d9.h>','#include "mirror_guard.h"','namespace NorthlightMirrorResources {']
    for interface in INTERFACES:
        body=source.split('DECLARE_INTERFACE_IID_('+interface+',')[1].split('};')[0]
        out += [f'class Forward{interface}:public {interface} {{','public:',f'    {interface}* real;', '    MirrorGate& gate; void(*unsafe)(void*,const char*); void* context;',f'    Forward{interface}({interface}* p,MirrorGate& g,void(*u)(void*,const char*),void* c):real(p),gate(g),unsafe(u),context(c){{}}']
        for m in re.finditer(r'STDMETHOD(?:_\(([^,]+),\s*(\w+)\)|\((\w+)\))\((.*?)\) PURE;',body,re.S):
            ret,special,normal,params=m.groups();ret=ret or 'HRESULT';name=special or normal
            params=re.sub(r'\bTHIS_?\b','',params).strip();decl=[];args=[]
            for i,param in enumerate(params.split(',') if params else []):
                param=' '.join(param.split())
                if param.endswith('*'):param+=f' arg{i}'
                args.append(re.search(r'(\w+)\s*$',param).group(1));decl.append(param)
            prefix='MirrorGuard lock(gate,MirrorSite::Resource); '  # 0.3.180 (D0): a census site; nested under a game call's guard
            if name=='GetPrivateData':prefix+='unsafe(context,"resource GetPrivateData may expose an unknown COM interface"); '
            out.append(f'    {ret} STDMETHODCALLTYPE {name}({", ".join(decl)}) override {{{prefix}return real->{name}({", ".join(args)});}}')
        out.append('};')
    out.append('}')
    (northlight_paths.GENERATED/'mirror_resource_forwarders.h').write_text('\n'.join(out)+'\n')
if __name__=='__main__':generate()
