"""Generate typed D3D9 forwarding methods from the installed Windows SDK header."""
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT.parent))
import northlight_paths  # noqa: E402
SDK = northlight_paths.windows_headers() / 'd3d9.h'

def generate():
    text = SDK.read_text()
    result = ['// Generated by generate_forwarders.py. Do not edit.', '#pragma once']
    for interface in ('IDirect3D9', 'IDirect3DDevice9', 'IDirect3DSwapChain9', 'IDirect3DVertexBuffer9', 'IDirect3DIndexBuffer9'):
        body = text.split('DECLARE_INTERFACE_IID_(' + interface + ',')[1].split('};')[0]
        result += [f'class Forward{interface} : public {interface} {{', 'public:',
                   f'    {interface}* real;', f'    explicit Forward{interface}({interface}* p) : real(p) {{}}']
        count = 0
        for m in re.finditer(r'STDMETHOD(?:_\(([^,]+),\s*(\w+)\)|\((\w+)\))\((.*?)\) PURE;', body, re.S):
            ret, special, normal, params = m.groups()
            ret, name = ret or 'HRESULT', special or normal
            params = re.sub(r'\bTHIS_?\b', '', params).strip()
            args, declarations = [], []
            for i, param in enumerate(params.split(',') if params else []):
                param = ' '.join(param.split())
                if param in ('D3DPRIMITIVETYPE', 'D3DLIGHT9*'):
                    param += f' arg{i}'
                arg = re.search(r'(\w+)\s*$', param).group(1)
                args.append(arg)
                declarations.append(param)
            result.append(f'    {ret} STDMETHODCALLTYPE {name}({", ".join(declarations)}) override {{ return real->{name}({", ".join(args)}); }}')
            count += 1
        assert count == {'IDirect3D9':17,'IDirect3DDevice9':119,'IDirect3DSwapChain9':10,'IDirect3DVertexBuffer9':14,'IDirect3DIndexBuffer9':14}[interface], (interface, count)
        result.append('};')
    # LF on every platform: the tree keeps LF line endings (hash gates compare raw bytes).
    with open(northlight_paths.GENERATED / 'forwarders.h', 'w', newline='\n') as f:
        f.write('\n'.join(result) + '\n')

if __name__ == '__main__':
    generate()
